#!/bin/sh

# Copyright (c) 2016, Justin D Holcomb All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Check for chyves updated
__check_for_chyves_update() {
	if [ "$_CHECK_FOR_UPDATES" != "off" ]; then
		[ "$_CHECK_FOR_UPDATES" = "daily" ] && local _num_of_updays=1
		[ "$_CHECK_FOR_UPDATES" = "monthly" ] && local _num_of_updays=30
		[ "$_CHECK_FOR_UPDATES" = "always" ] && local _num_of_updays=0
		[ -z "$_num_of_updays" ] && local _num_of_updays=7
		local _check_again_date=`date -v -${_num_of_updays}d +"%Y%m%d"`

		if [ "$_CHECK_FOR_UPDATES_LAST_CHECK_STATUS" -eq 1 ]; then
			echo "NEWER VERSION of chyves available. Check $_PROJECT_URL_GIT/tree/$_VERSION_BRANCH"
		elif [ "$_check_again_date" -ge "$_CHECK_FOR_UPDATES_LAST_CHECK" ]; then
			echo "Checking for newer version of chyves on the $_VERSION_BRANCH branch from $_CHECK_FOR_UPDATES_URL."
			local _fetched_version_library=$( fetch --timeout $_CHECK_FOR_UPDATES_TIMEOUT_SECONDS --quiet -o - --user-agent="chyves $_VERSION_LONG ( $_OS $_OS_VERSION_REL $_OS_VERSION_DATE $_OS_VERSION_REV $_OS_VERSION_FREENAS ; ${_CHECK_FOR_UPDATES_UNIQUE_ID}; )" $_CHECK_FOR_UPDATES_URL )
			local _grepped_version=$( echo "$_fetched_version_library" | grep '$_VERSION_INT' | cut -d'"' -f1 )

			if [ -z "$_grepped_version" ]; then
				echo "Unable to obtain current available version information from $_CHECK_FOR_UPDATES_URL after $_CHECK_FOR_UPDATES_TIMEOUT_SECONDS seconds."
			elif [ "$_grepped_version" -gt "$_VERSION_INT" ]; then
				__write_property_value_to_config_file "global" "check_for_updates_last_check" "$_DATE_YMD"
				echo "NEWER VERSION of chyves available. Check $_PROJECT_URL_GIT/tree/$_VERSION_BRANCH"
				__write_property_value_to_config_file "global" "check_for_updates_last_check_status" "1"
			elif [ "$_grepped_version" -eq "$_VERSION_INT" ]; then
				local _next_check_date=`date -v +${_num_of_updays}d +"%Y%m%d"`
				__write_property_value_to_config_file "global" "check_for_updates_last_check" "$_DATE_YMD"
				echo "On current version, will check again on: $_next_check_date"
				__write_property_value_to_config_file "global" "check_for_updates_last_check_status" "0"
			fi
		fi
	fi
}
